name: mobilepos
description: Mobile POS Offline untuk UMKM
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Database
  sqflite: ^2.3.3
  path: ^1.9.0

  # Barcode Scanner
  mobile_scanner: ^5.2.3

  # Bluetooth Thermal Print
  flutter_blue_plus: ^1.32.12
  esc_pos_utils_plus: ^2.0.4

  # Excel Export
  excel: ^4.0.6

  # File & Share
  path_provider: ^2.1.3
  share_plus: ^9.0.0
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  image: ^4.0.15
  shared_preferences: ^2.3.2

  # HTTP / API
  http: ^1.2.0

  # Environment
  flutter_dotenv: ^5.1.0

  # UI
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
